### ISSUE TITLE
Error: uninitialized constant BitsOnTheRun::Call::VERSION

### ISSUE THREAD

**Issue by albertoperdomo** [adriandulic/bitsontherun#1]
Hi, I'm using bitsontherun (0.1.0).

Loading development environment (Rails 3.0.4)
ruby-1.9.2-p0 > BitsOnTheRun::call('version')
NameError: uninitialized constant BitsOnTheRun::Call::VERSION
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/bitsontherun-0.1.0/lib/bitsontherun/call.rb:12:in `initialize'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/bitsontherun-0.1.0/lib/bitsontherun/api.rb:4:in`new'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/bitsontherun-0.1.0/lib/bitsontherun/api.rb:4:in `initialize'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/bitsontherun-0.1.0/lib/bitsontherun.rb:54:in`new'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/bitsontherun-0.1.0/lib/bitsontherun.rb:54:in `call'
    from (irb):1
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/railties-3.0.4/lib/rails/commands/console.rb:44:in`start'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/railties-3.0.4/lib/rails/commands/console.rb:8:in `start'
    from /Users/alberto/.rvm/gems/ruby-1.9.2-p0@rails3/gems/railties-3.0.4/lib/rails/commands.rb:23:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by adriandulic** [comment]
Did you specified your API key & secret?

**Comment by albertoperdomo** [comment]
Yes,
in config/initializers/bits_on_the_run.rb

```
BitsOnTheRun.key = "xxxx"
BitsOnTheRun.secret = "xxxx"
```

**Comment by adriandulic** [comment]
It was an issue with ruby 1.9.2.
Try bitsontherun v0.1.1.

**Comment by albertoperdomo** [comment]
Seems to work fine in the new version.
Thanks!
