### ISSUE TITLE
Passing params

### ISSUE THREAD

**Issue by ThomasBush** [adriandulic/bitsontherun#3]
I was wondering if there is a way for me to pass params.  I don't currently see one, but need to return more that the default 50 videos.  I want to pass the param `result_limit` to return the amount of videos I need.

**Comment by adriandulic** [comment]
You should be able to pass additional params as a second argument, like here:
`BitsOnTheRun::call('videos/update', :param1 => "value1")`

However the BOTR API might changed since this gem was released. In this case you could work on a patch and submit a pull request :+1:

**Comment by ThomasBush** [comment]
Wow that was painfully obvious, sorry.  I will see what I can do to help.
